/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author hyper
 */
public class Formulas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Perfumes
     */
public Formulas() {
    initComponents();
    
    // Agregar listener para detectar cuando se cambia de pestaña
    jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            // Verificar si se seleccionó la pestaña "Mostrar todo" (índice 4)
            if (jTabbedPane1.getSelectedIndex() == 4) {
                cargarTablaFormulas();
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        AltaFormulas = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        TxtObservacionesFormula = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        TxtVersionFormula = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<>();
        jLabel57 = new javax.swing.JLabel();
        TxTFechaRegistroF = new javax.swing.JFormattedTextField();
        jLabel59 = new javax.swing.JLabel();
        TxtIDFormula = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaContiene = new javax.swing.JTable();
        BtnGuardarFormula = new javax.swing.JButton();
        BtnLimpiarAlta = new javax.swing.JButton();
        BtnAgregarFilaF = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        BtnEliminarFilaAlta = new javax.swing.JButton();
        BajaFormulas = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        TxtVersionFormula1 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jComboBox18 = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        FTxTFechaRegistro1 = new javax.swing.JFormattedTextField();
        jLabel61 = new javax.swing.JLabel();
        TxtIDFormula1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaContiene1 = new javax.swing.JTable();
        BtnGuardarFormula1 = new javax.swing.JButton();
        BtnLimpiarFormulaBaja = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        CambiosFormulas = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        TxtVersionFormula2 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox<>();
        jLabel66 = new javax.swing.JLabel();
        FTxTFechaRegistro2 = new javax.swing.JFormattedTextField();
        jLabel67 = new javax.swing.JLabel();
        TxtIDFormula2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaContiene2 = new javax.swing.JTable();
        BtnGuardarFormula2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        BtnAgregarFilaF1 = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        BtnEliminarFilaCambios = new javax.swing.JButton();
        BuscarFormulas = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        TxtVersionFormula3 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jComboBox20 = new javax.swing.JComboBox<>();
        jLabel72 = new javax.swing.JLabel();
        FTxTFechaRegistro3 = new javax.swing.JFormattedTextField();
        jLabel73 = new javax.swing.JLabel();
        TxtIDFormula3 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaContiene3 = new javax.swing.JTable();
        BtnGuardarFormula3 = new javax.swing.JButton();
        BtnLimpiarBuscar = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        MostrarFormulas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(750, 550));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(750, 550));

        AltaFormulas.setPreferredSize(new java.awt.Dimension(737, 550));

        jLabel51.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel51.setText("Observaciones:");

        TxtObservacionesFormula.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtObservacionesFormula.addActionListener(this::TxtObservacionesFormulaActionPerformed);

        jLabel52.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel52.setText("Versión:");

        TxtVersionFormula.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtVersionFormula.addActionListener(this::TxtVersionFormulaActionPerformed);

        jLabel54.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel54.setText("Perfume:");

        jComboBox17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floral", "Amaderado", "Cítrica" }));

        jLabel57.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel57.setText("Fecha de registro:");

        TxTFechaRegistroF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        TxTFechaRegistroF.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxTFechaRegistroF.addActionListener(this::TxTFechaRegistroFActionPerformed);

        jLabel59.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel59.setText("ID de la fórmula:");

        TxtIDFormula.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula.addActionListener(this::TxtIDFormulaActionPerformed);

        jScrollPane3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingrediente", "Nota", "Proporción "
            }
        ));
        jScrollPane3.setViewportView(TablaContiene);

        BtnGuardarFormula.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula.setText("Guardar");
        BtnGuardarFormula.addActionListener(this::BtnGuardarFormulaActionPerformed);

        BtnLimpiarAlta.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnLimpiarAlta.setText("Limpiar");
        BtnLimpiarAlta.addActionListener(this::BtnLimpiarAltaActionPerformed);

        BtnAgregarFilaF.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnAgregarFilaF.setText("Agregar fila");
        BtnAgregarFilaF.addActionListener(this::BtnAgregarFilaFActionPerformed);

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel55.setText("Ingredientes:");

        BtnEliminarFilaAlta.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnEliminarFilaAlta.setText("Eliminar Fila");
        BtnEliminarFilaAlta.addActionListener(this::BtnEliminarFilaAltaActionPerformed);

        javax.swing.GroupLayout AltaFormulasLayout = new javax.swing.GroupLayout(AltaFormulas);
        AltaFormulas.setLayout(AltaFormulasLayout);
        AltaFormulasLayout.setHorizontalGroup(
            AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltaFormulasLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AltaFormulasLayout.createSequentialGroup()
                        .addComponent(BtnGuardarFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEliminarFilaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAgregarFilaF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimpiarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AltaFormulasLayout.createSequentialGroup()
                        .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel52)
                                .addComponent(jLabel57)
                                .addComponent(jLabel59)
                                .addComponent(jLabel51))
                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtIDFormula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtVersionFormula, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxTFechaRegistroF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtObservacionesFormula)
                            .addComponent(jComboBox17, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(118, 118, 118))
        );
        AltaFormulasLayout.setVerticalGroup(
            AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaFormulasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(TxtIDFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(TxtVersionFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(TxTFechaRegistroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(TxtObservacionesFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addGap(20, 20, 20)
                .addComponent(jLabel55)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addGroup(AltaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula)
                    .addComponent(BtnLimpiarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarFilaF)
                    .addComponent(BtnEliminarFilaAlta))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Alta", AltaFormulas);

        jLabel53.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel53.setText("Observaciones:");

        jTextField22.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField22.setEnabled(false);
        jTextField22.addActionListener(this::jTextField22ActionPerformed);

        jLabel56.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel56.setText("Versión:");

        TxtVersionFormula1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtVersionFormula1.setEnabled(false);
        TxtVersionFormula1.addActionListener(this::TxtVersionFormula1ActionPerformed);

        jLabel58.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel58.setText("Perfume:");

        jComboBox18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floral", "Amaderado", "Cítrica" }));
        jComboBox18.setEnabled(false);

        jLabel60.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel60.setText("Fecha de registro:");

        FTxTFechaRegistro1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaRegistro1.setEnabled(false);
        FTxTFechaRegistro1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaRegistro1.addActionListener(this::FTxTFechaRegistro1ActionPerformed);

        jLabel61.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel61.setText("ID de la fórmula:");

        TxtIDFormula1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula1.addActionListener(this::TxtIDFormula1ActionPerformed);

        jScrollPane4.setEnabled(false);
        jScrollPane4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingrediente", "Nota", "Proporción "
            }
        ));
        TablaContiene1.setEnabled(false);
        jScrollPane4.setViewportView(TablaContiene1);

        BtnGuardarFormula1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula1.setText("Eliminar");
        BtnGuardarFormula1.addActionListener(this::BtnGuardarFormula1ActionPerformed);

        BtnLimpiarFormulaBaja.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnLimpiarFormulaBaja.setText("Limpiar");
        BtnLimpiarFormulaBaja.addActionListener(this::BtnLimpiarFormulaBajaActionPerformed);

        jLabel62.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel62.setText("Ingredientes:");

        javax.swing.GroupLayout BajaFormulasLayout = new javax.swing.GroupLayout(BajaFormulas);
        BajaFormulas.setLayout(BajaFormulasLayout);
        BajaFormulasLayout.setHorizontalGroup(
            BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BajaFormulasLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BajaFormulasLayout.createSequentialGroup()
                        .addComponent(BtnGuardarFormula1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnLimpiarFormulaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BajaFormulasLayout.createSequentialGroup()
                        .addComponent(jLabel62)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BajaFormulasLayout.createSequentialGroup()
                        .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(29, 29, 29)
                        .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtVersionFormula1)
                            .addComponent(FTxTFechaRegistro1)
                            .addComponent(jTextField22)
                            .addComponent(TxtIDFormula1)
                            .addComponent(jComboBox18, 0, 393, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addGap(118, 118, 118))
        );
        BajaFormulasLayout.setVerticalGroup(
            BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajaFormulasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(TxtIDFormula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(TxtVersionFormula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(FTxTFechaRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel62)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addGroup(BajaFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula1)
                    .addComponent(BtnLimpiarFormulaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Baja", BajaFormulas);

        CambiosFormulas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel63.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel63.setText("Observaciones:");

        jTextField23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField23.setEnabled(false);
        jTextField23.addActionListener(this::jTextField23ActionPerformed);

        jLabel64.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel64.setText("Versión:");

        TxtVersionFormula2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtVersionFormula2.setEnabled(false);
        TxtVersionFormula2.addActionListener(this::TxtVersionFormula2ActionPerformed);

        jLabel65.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel65.setText("Perfume:");

        jComboBox19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floral", "Amaderado", "Cítrica" }));
        jComboBox19.setEnabled(false);

        jLabel66.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel66.setText("Fecha de registro:");

        FTxTFechaRegistro2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaRegistro2.setEnabled(false);
        FTxTFechaRegistro2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaRegistro2.addActionListener(this::FTxTFechaRegistro2ActionPerformed);

        jLabel67.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel67.setText("ID de la fórmula:");

        TxtIDFormula2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula2.addActionListener(this::TxtIDFormula2ActionPerformed);

        jScrollPane5.setEnabled(false);
        jScrollPane5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingrediente", "Nota", "Proporción "
            }
        ));
        TablaContiene2.setEnabled(false);
        jScrollPane5.setViewportView(TablaContiene2);

        BtnGuardarFormula2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula2.setText("Modificar");
        BtnGuardarFormula2.addActionListener(this::BtnGuardarFormula2ActionPerformed);

        jButton15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton15.setText("Limpiar");
        jButton15.addActionListener(this::jButton15ActionPerformed);

        BtnAgregarFilaF1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnAgregarFilaF1.setText("Agregar fila");
        BtnAgregarFilaF1.setEnabled(false);
        BtnAgregarFilaF1.addActionListener(this::BtnAgregarFilaF1ActionPerformed);

        jLabel68.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel68.setText("Ingredientes:");

        BtnEliminarFilaCambios.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnEliminarFilaCambios.setText("Eliminar Fila");

        javax.swing.GroupLayout CambiosFormulasLayout = new javax.swing.GroupLayout(CambiosFormulas);
        CambiosFormulas.setLayout(CambiosFormulasLayout);
        CambiosFormulasLayout.setHorizontalGroup(
            CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiosFormulasLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CambiosFormulasLayout.createSequentialGroup()
                        .addComponent(BtnGuardarFormula2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEliminarFilaCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAgregarFilaF1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CambiosFormulasLayout.createSequentialGroup()
                        .addComponent(jLabel68)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CambiosFormulasLayout.createSequentialGroup()
                        .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(29, 29, 29)
                        .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtVersionFormula2)
                            .addComponent(FTxTFechaRegistro2)
                            .addComponent(jTextField23)
                            .addComponent(TxtIDFormula2)
                            .addComponent(jComboBox19, 0, 393, Short.MAX_VALUE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addGap(118, 118, 118))
        );
        CambiosFormulasLayout.setVerticalGroup(
            CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiosFormulasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(TxtIDFormula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(TxtVersionFormula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(FTxTFechaRegistro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel68)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addGroup(CambiosFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula2)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregarFilaF1)
                    .addComponent(BtnEliminarFilaCambios))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Cambios", CambiosFormulas);

        jLabel69.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel69.setText("Observaciones:");

        jTextField24.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField24.setEnabled(false);
        jTextField24.addActionListener(this::jTextField24ActionPerformed);

        jLabel70.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel70.setText("Versión:");

        TxtVersionFormula3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtVersionFormula3.setEnabled(false);
        TxtVersionFormula3.addActionListener(this::TxtVersionFormula3ActionPerformed);

        jLabel71.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel71.setText("Perfume:");

        jComboBox20.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floral", "Amaderado", "Cítrica" }));
        jComboBox20.setEnabled(false);

        jLabel72.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel72.setText("Fecha de registro:");

        FTxTFechaRegistro3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaRegistro3.setEnabled(false);
        FTxTFechaRegistro3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaRegistro3.addActionListener(this::FTxTFechaRegistro3ActionPerformed);

        jLabel73.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel73.setText("ID de la fórmula:");

        TxtIDFormula3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula3.addActionListener(this::TxtIDFormula3ActionPerformed);

        jScrollPane6.setEnabled(false);
        jScrollPane6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingrediente", "Nota", "Proporción "
            }
        ));
        TablaContiene3.setEnabled(false);
        jScrollPane6.setViewportView(TablaContiene3);

        BtnGuardarFormula3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula3.setText("Buscar");
        BtnGuardarFormula3.addActionListener(this::BtnGuardarFormula3ActionPerformed);

        BtnLimpiarBuscar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnLimpiarBuscar.setText("Limpiar");
        BtnLimpiarBuscar.addActionListener(this::BtnLimpiarBuscarActionPerformed);

        jLabel74.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel74.setText("Ingredientes:");

        javax.swing.GroupLayout BuscarFormulasLayout = new javax.swing.GroupLayout(BuscarFormulas);
        BuscarFormulas.setLayout(BuscarFormulasLayout);
        BuscarFormulasLayout.setHorizontalGroup(
            BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarFormulasLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BuscarFormulasLayout.createSequentialGroup()
                        .addComponent(BtnGuardarFormula3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnLimpiarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BuscarFormulasLayout.createSequentialGroup()
                        .addComponent(jLabel74)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BuscarFormulasLayout.createSequentialGroup()
                        .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel72, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel73, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel69, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(29, 29, 29)
                        .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtVersionFormula3)
                            .addComponent(FTxTFechaRegistro3)
                            .addComponent(jTextField24)
                            .addComponent(TxtIDFormula3)
                            .addComponent(jComboBox20, 0, 393, Short.MAX_VALUE)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addGap(118, 118, 118))
        );
        BuscarFormulasLayout.setVerticalGroup(
            BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarFormulasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(TxtIDFormula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(TxtVersionFormula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(FTxTFechaRegistro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel74)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addGroup(BuscarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula3)
                    .addComponent(BtnLimpiarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Buscar", BuscarFormulas);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Fórmula", "Versión", "Observaciones", "ID Perfume"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout MostrarFormulasLayout = new javax.swing.GroupLayout(MostrarFormulas);
        MostrarFormulas.setLayout(MostrarFormulasLayout);
        MostrarFormulasLayout.setHorizontalGroup(
            MostrarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        MostrarFormulasLayout.setVerticalGroup(
            MostrarFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mostrar todo", MostrarFormulas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarFilaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFilaFActionPerformed
        // TODO add your handling code here
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaContiene.getModel();
        modelo.addRow(new Object[]{"", "", ""});
    }//GEN-LAST:event_BtnAgregarFilaFActionPerformed

    private void BtnLimpiarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarAltaActionPerformed
        // TODO add your handling code here:
            TxtIDFormula.setText("");
            TxtVersionFormula.setText("");
            TxTFechaRegistroF.setText("");
            TxtObservacionesFormula.setText("");
            
            if (jComboBox17 != null) 
            {
                jComboBox17.setSelectedIndex(0);
            }
            
            JOptionPane.showMessageDialog(this, "Campos limpiados", "Limpiar", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnLimpiarAltaActionPerformed

    private void BtnGuardarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormulaActionPerformed
    try {
        String idStr = TxtIDFormula.getText().trim();
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de fórmula", "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(idStr);
        String version = TxtVersionFormula.getText().trim();
        String observaciones = TxtObservacionesFormula.getText().trim();
        String fechaStr = TxTFechaRegistroF.getText().trim();

        if (version.isEmpty() || fechaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Convertir fecha
        java.util.Date fechaUtil = new SimpleDateFormat("dd/MM/yyyy").parse(fechaStr);
        
        // Obtener ID del perfume desde el combo
        String perfumeSeleccionado = jComboBox17.getSelectedItem().toString();
        int idPerfume = 1; // valor por defecto
        switch (perfumeSeleccionado) {
            case "Floral": idPerfume = 1; break;
            case "Amaderado": idPerfume = 2; break;
            case "Cítrica": idPerfume = 3; break;
        }

        // Crear y guardar la fórmula
        Modelos.Formula formula = new Modelos.Formula(version, observaciones, fechaUtil, id, idPerfume);
        formula.guardar();

        JOptionPane.showMessageDialog(this, "Fórmula guardada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        BtnLimpiarAltaActionPerformed(null);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número válido", "Error de formato", JOptionPane.ERROR_MESSAGE);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use dd/MM/yyyy", "Error de fecha", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnGuardarFormulaActionPerformed

    private void TxtIDFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormulaActionPerformed

    private void TxtVersionFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVersionFormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVersionFormulaActionPerformed

    private void TxtObservacionesFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtObservacionesFormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtObservacionesFormulaActionPerformed

    private void TxTFechaRegistroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxTFechaRegistroFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxTFechaRegistroFActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
 int fila = jTable2.getSelectedRow();
    
    if (fila != -1) {
 
        String id = jTable2.getValueAt(fila, 0).toString();
        mostrarIngredientesFormula(id);
    }
}         
private void mostrarIngredientesFormula(String id) {
    javax.swing.JDialog ventanaDetalle = new javax.swing.JDialog();
    ventanaDetalle.setTitle("Ingredientes de la Fórmula " + id);
    ventanaDetalle.setSize(500, 300);
    ventanaDetalle.setLocationRelativeTo(this);
    ventanaDetalle.setModal(true); 

    String[] columnas = {"ID Ingrediente", "Nota", "Proporción"};
    javax.swing.table.DefaultTableModel modeloDetalle = new javax.swing.table.DefaultTableModel(columnas, 0);
    javax.swing.JTable tablaDetalle = new javax.swing.JTable(modeloDetalle);
    
    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tablaDetalle);
    
    ventanaDetalle.add(scroll);
    ventanaDetalle.setVisible(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void TxtVersionFormula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVersionFormula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVersionFormula1ActionPerformed

    private void FTxTFechaRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaRegistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaRegistro1ActionPerformed

    private void TxtIDFormula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula1ActionPerformed

    private void BtnGuardarFormula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormula1ActionPerformed
        // TODO add your handling code here:
            try {
        // Validar que el ID no esté vacío
        if (TxtIDFormula1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor, ingrese el ID de la fórmula a eliminar",
                "Campo requerido",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idFormula = Integer.parseInt(TxtIDFormula1.getText().trim());
        
        // Primero verificar si existe la fórmula
        Modelos.Formula formula = new Modelos.Formula();
        if (!formula.Buscar(idFormula)) {
            JOptionPane.showMessageDialog(this,
                "No existe una fórmula con el ID: " + idFormula,
                "Fórmula no encontrada",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirmar eliminación mostrando algunos datos
        String mensaje = "¿Seguro que desea eliminar esta fórmula?\n\n" +
                        "ID: " + formula.getId_formula() + "\n" +
                        "Versión: " + formula.getVersion() + "\n" +
                        "Observaciones: " + formula.getObservaciones();
        
        int confirmar = JOptionPane.showConfirmDialog(this, 
            mensaje,
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirmar == JOptionPane.YES_OPTION) {
            // Eliminar la fórmula
            formula.Borrar(idFormula);
            
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, 
                "Fórmula eliminada exitosamente.",
                "Eliminación exitosa",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar los campos
            BtnLimpiarFormulaBajaActionPerformed(null);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido",
            "Error de formato",
            JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error al eliminar: " + e.getMessage(),
            "Error de base de datos",
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnGuardarFormula1ActionPerformed

    private void BtnLimpiarFormulaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarFormulaBajaActionPerformed
        // TODO add your handling code here:
            TxtIDFormula.setText("");
            TxtVersionFormula.setText("");
            TxTFechaRegistroF.setText("");
            TxtObservacionesFormula.setText("");
            
            if (jComboBox17 != null) 
            {
                jComboBox17.setSelectedIndex(0);
            }
            
            JOptionPane.showMessageDialog(this, "Campos limpiados", "Limpiar", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnLimpiarFormulaBajaActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void TxtVersionFormula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVersionFormula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVersionFormula2ActionPerformed

    private void FTxTFechaRegistro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaRegistro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaRegistro2ActionPerformed

    private void TxtIDFormula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula2ActionPerformed

    private void BtnGuardarFormula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormula2ActionPerformed
        // TODO add your handling code here:
           try {
        // Validar que el ID no esté vacío
        String idStr = TxtIDFormula2.getText().trim();
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor, ingrese el ID de la fórmula a modificar",
                "Campo requerido",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(idStr);

        // Buscar la fórmula actual
        Modelos.Formula formula = new Modelos.Formula();
        if (!formula.Buscar(id)) {
            JOptionPane.showMessageDialog(this,
                "No existe una fórmula con el ID: " + id,
                "Fórmula no encontrada",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmar que quiere modificar
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Seguro que desea modificar esta fórmula?\n" +
            "ID: " + formula.getId_formula() + "\n" +
            "Versión actual: " + formula.getVersion(),
            "Confirmar modificación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        // Obtener los nuevos valores del formulario
        String nuevaVersion = TxtVersionFormula2.getText().trim();
        String nuevasObservaciones = jTextField23.getText().trim(); // ← ¡Ojo! Este campo es jTextField23, no TxtObservacionesFormula
        String fechaStr = FTxTFechaRegistro2.getText().trim();

        if (nuevaVersion.isEmpty() || fechaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Complete todos los campos obligatorios",
                "Campos incompletos",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Convertir fecha
        java.util.Date fechaUtil = new SimpleDateFormat("dd/MM/yyyy").parse(fechaStr);

        // Obtener ID del perfume desde el combo
        String perfumeSeleccionado = jComboBox19.getSelectedItem().toString();
        int idPerfume = 1; // valor por defecto
        switch (perfumeSeleccionado) {
            case "Floral": idPerfume = 1; break;
            case "Amaderado": idPerfume = 2; break;
            case "Cítrica": idPerfume = 3; break;
        }

        // Actualizar los datos en el objeto Formula
        formula.setVersion(nuevaVersion);
        formula.setObservaciones(nuevasObservaciones);
        formula.setFecha_registro(fechaUtil);
        formula.setId_perfume(idPerfume);

        // Guardar los cambios en la base de datos
        formula.Modificar();

        JOptionPane.showMessageDialog(this,
            "Fórmula modificada exitosamente",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE);

        // Limpiar los campos después de modificar
        BtnLimpiarFormulaBajaActionPerformed(null); // Reutilizamos el limpiador de Baja, que limpia los campos

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido",
            "Error de formato",
            JOptionPane.ERROR_MESSAGE);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this,
            "Formato de fecha inválido. Use dd/MM/yyyy",
            "Error de fecha",
            JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Error al modificar en la base de datos: " + e.getMessage(),
            "Error SQL",
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error inesperado: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_BtnGuardarFormula2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void BtnAgregarFilaF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFilaF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarFilaF1ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void TxtVersionFormula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtVersionFormula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtVersionFormula3ActionPerformed

    private void FTxTFechaRegistro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaRegistro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaRegistro3ActionPerformed

    private void TxtIDFormula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula3ActionPerformed

    private void BtnGuardarFormula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormula3ActionPerformed
        // TODO add your handling code here:
       try {
        if (TxtIDFormula3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor, ingrese un ID de fórmula",
                "Campo requerido",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int id = Integer.parseInt(TxtIDFormula3.getText().trim());
        Modelos.Formula formula = new Modelos.Formula();
        
        if (formula.Buscar(id)) {
            // Llenar los campos con la información encontrada
            TxtVersionFormula3.setText(formula.getVersion());
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            FTxTFechaRegistro3.setText(sdf.format(formula.getFecha_registro()));
            
            jTextField24.setText(formula.getObservaciones());
            
            // Buscar el perfume
            int idPerfume = formula.getId_perfume();
            String nombrePerfume = "";
            switch(idPerfume) {
                case 1:
                    nombrePerfume = "Floral";
                    break;
                case 2:
                    nombrePerfume = "Amaderado";
                    break;
                case 3:
                    nombrePerfume = "Cítrica";
                    break;
                default:
                    nombrePerfume = "Floral";
            }
            jComboBox20.setSelectedItem(nombrePerfume);
            

            try
                {
                    ResultSet rsIngredientes = formula.MostrarIngredientes(id);
                    javax.swing.table.DefaultTableModel modeloIngredientes =
                    (javax.swing.table.DefaultTableModel) TablaContiene3.getModel();
    

                    modeloIngredientes.setRowCount(0);

                    while (rsIngredientes.next()) {
                    Object[] filaIngrediente = new Object[3];
                     filaIngrediente[0] = rsIngredientes.getString("nombre");
                    filaIngrediente[1] = rsIngredientes.getString("nota");
                    filaIngrediente[2] = rsIngredientes.getDouble("proporcion");
                    modeloIngredientes.addRow(filaIngrediente);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                    "Error al cargar ingredientes: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            
            JOptionPane.showMessageDialog(this,
                "Fórmula encontrada exitosamente",
                "Búsqueda exitosa",
                JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(this, 
                "No existe una fórmula con el ID: " + id,
                "Fórmula no encontrada",
                JOptionPane.WARNING_MESSAGE);
            
            // Limpiar los campos
            TxtIDFormula3.setText("");
            TxtVersionFormula3.setText("");
            FTxTFechaRegistro3.setText("");
            jTextField24.setText("");
            jComboBox20.setSelectedIndex(0);
            
            // Limpiar tabla de ingredientes
            javax.swing.table.DefaultTableModel modeloIngredientes = 
                (javax.swing.table.DefaultTableModel) TablaContiene3.getModel();
            modeloIngredientes.setRowCount(0);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "El ID debe ser un número válido",
            "Error de formato",
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al buscar: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnGuardarFormula3ActionPerformed

    private void BtnLimpiarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarBuscarActionPerformed
        // TODO add your handling code here:
        TxtIDFormula3.setText("");
    TxtVersionFormula3.setText("");
    FTxTFechaRegistro3.setText("");
    jTextField24.setText("");
    
    if (jComboBox20 != null) {
        jComboBox20.setSelectedIndex(0);
    }
    
    // Limpiar la tabla de ingredientes si la usas
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaContiene3.getModel();
    modelo.setRowCount(0);
    
    JOptionPane.showMessageDialog(this, 
        "Campos limpiados", 
        "Limpiar", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnLimpiarBuscarActionPerformed

    private void BtnEliminarFilaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarFilaAltaActionPerformed
        // TODO add your handling code here:
            int filaSeleccionada = TablaContiene.getSelectedRow();
            
            if (filaSeleccionada == -1) 
            {
                JOptionPane.showMessageDialog( this,"selecciona una fila para eliminar", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar esta fila?", "Confirmar eliminación",JOptionPane.YES_NO_OPTION);
            
            if (confirmacion == JOptionPane.YES_OPTION) 
            {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaContiene.getModel();
                modelo.removeRow(filaSeleccionada);
            }
    }//GEN-LAST:event_BtnEliminarFilaAltaActionPerformed

public void cargarTablaFormulas() {
    try {
        Modelos.Formula formula = new Modelos.Formula();
        ResultSet rs = formula.Mostrar();
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
        
        while (rs.next()) {
            Object[] fila = new Object[4];
            fila[0] = rs.getInt("id_formula");
            fila[1] = rs.getString("version");
            fila[2] = rs.getString("observaciones");
            fila[3] = rs.getInt("perfumes_id_perfume");  // ← CAMBIO AQUÍ
            
            modelo.addRow(fila);
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error al cargar los datos: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }  
}

private void habilitarCamposCambios() {
    TxtVersionFormula2.setEnabled(true);
    jTextField23.setEnabled(true);
    FTxTFechaRegistro2.setEnabled(true);
    jComboBox19.setEnabled(true);
    BtnAgregarFilaF1.setEnabled(true);
    BtnEliminarFilaCambios.setEnabled(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AltaFormulas;
    private javax.swing.JPanel BajaFormulas;
    private javax.swing.JButton BtnAgregarFilaF;
    private javax.swing.JButton BtnAgregarFilaF1;
    private javax.swing.JButton BtnEliminarFilaAlta;
    private javax.swing.JButton BtnEliminarFilaCambios;
    private javax.swing.JButton BtnGuardarFormula;
    private javax.swing.JButton BtnGuardarFormula1;
    private javax.swing.JButton BtnGuardarFormula2;
    private javax.swing.JButton BtnGuardarFormula3;
    private javax.swing.JButton BtnLimpiarAlta;
    private javax.swing.JButton BtnLimpiarBuscar;
    private javax.swing.JButton BtnLimpiarFormulaBaja;
    private javax.swing.JPanel BuscarFormulas;
    private javax.swing.JPanel CambiosFormulas;
    private javax.swing.JFormattedTextField FTxTFechaRegistro1;
    private javax.swing.JFormattedTextField FTxTFechaRegistro2;
    private javax.swing.JFormattedTextField FTxTFechaRegistro3;
    private javax.swing.JPanel MostrarFormulas;
    private javax.swing.JTable TablaContiene;
    private javax.swing.JTable TablaContiene1;
    private javax.swing.JTable TablaContiene2;
    private javax.swing.JTable TablaContiene3;
    private javax.swing.JFormattedTextField TxTFechaRegistroF;
    private javax.swing.JTextField TxtIDFormula;
    private javax.swing.JTextField TxtIDFormula1;
    private javax.swing.JTextField TxtIDFormula2;
    private javax.swing.JTextField TxtIDFormula3;
    private javax.swing.JTextField TxtObservacionesFormula;
    private javax.swing.JTextField TxtVersionFormula;
    private javax.swing.JTextField TxtVersionFormula1;
    private javax.swing.JTextField TxtVersionFormula2;
    private javax.swing.JTextField TxtVersionFormula3;
    private javax.swing.JButton jButton15;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    // End of variables declaration//GEN-END:variables
}

