/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author hyper
 */
public class Lotes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Perfumes
     */
    public Lotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        AltaLotesProduccion = new javax.swing.JPanel();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jFormattedTextField20 = new javax.swing.JFormattedTextField();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        BajaLotesProduccion = new javax.swing.JPanel();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jFormattedTextField23 = new javax.swing.JFormattedTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        CambiosLotesProduccion = new javax.swing.JPanel();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jFormattedTextField24 = new javax.swing.JFormattedTextField();
        jFormattedTextField25 = new javax.swing.JFormattedTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        BuscarLotesProduccion = new javax.swing.JPanel();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jFormattedTextField26 = new javax.swing.JFormattedTextField();
        jFormattedTextField27 = new javax.swing.JFormattedTextField();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        MostrarLotesProduccion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        AltaLotesProduccion.setPreferredSize(new java.awt.Dimension(752, 500));

        jFormattedTextField16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel50.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel50.setText("Cantidad producida:");

        jLabel51.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel51.setText("Control de calidad:");

        jTextField20.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField20.addActionListener(this::jTextField20ActionPerformed);

        jTextField21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField21.addActionListener(this::jTextField21ActionPerformed);

        jLabel52.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel52.setText("Fecha inicio:");

        jLabel53.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel53.setText("Observaciones:");

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel55.setText("Fecha finalización:");

        jButton12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton12.setText("Guardar");
        jButton12.addActionListener(this::jButton12ActionPerformed);

        jLabel58.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel58.setText("Costo total:");

        jLabel59.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel59.setText("ID del lote:");

        jTextField23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField23.addActionListener(this::jTextField23ActionPerformed);

        jButton13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton13.setText("Limpiar");
        jButton13.addActionListener(this::jButton13ActionPerformed);

        jFormattedTextField20.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField20.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jFormattedTextField21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel82.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel82.setText("ID perfume:");

        jLabel83.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel83.setText("ID empleado:");

        jTextField22.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField22.addActionListener(this::jTextField22ActionPerformed);

        jTextField24.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField24.addActionListener(this::jTextField24ActionPerformed);

        jTextField25.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField25.addActionListener(this::jTextField25ActionPerformed);

        javax.swing.GroupLayout AltaLotesProduccionLayout = new javax.swing.GroupLayout(AltaLotesProduccion);
        AltaLotesProduccion.setLayout(AltaLotesProduccionLayout);
        AltaLotesProduccionLayout.setHorizontalGroup(
            AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaLotesProduccionLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel82)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel55)
                    .addComponent(jLabel59)
                    .addComponent(jLabel50)
                    .addComponent(jLabel58)
                    .addComponent(jLabel83))
                .addGap(21, 21, 21)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField20)
                    .addComponent(jFormattedTextField21)
                    .addComponent(jTextField20)
                    .addComponent(jFormattedTextField16)
                    .addComponent(jTextField21)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltaLotesProduccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField23)
                    .addComponent(jTextField22)
                    .addComponent(jTextField24)
                    .addComponent(jTextField25))
                .addGap(96, 96, 96))
        );
        AltaLotesProduccionLayout.setVerticalGroup(
            AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaLotesProduccionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jTextField23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jFormattedTextField20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jFormattedTextField21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jTextField20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jFormattedTextField16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jTextField21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AltaLotesProduccionLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel82)
                            .addComponent(jTextField24))
                        .addGap(18, 18, 18)
                        .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel83)
                            .addComponent(jTextField25)))
                    .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel53)
                        .addComponent(jTextField22)))
                .addGap(18, 18, 18)
                .addGroup(AltaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Alta", AltaLotesProduccion);

        BajaLotesProduccion.setPreferredSize(new java.awt.Dimension(752, 500));

        jFormattedTextField17.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel54.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel54.setText("Cantidad producida:");

        jLabel56.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel56.setText("Control de calidad:");

        jTextField26.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField26.addActionListener(this::jTextField26ActionPerformed);

        jTextField27.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField27.addActionListener(this::jTextField27ActionPerformed);

        jLabel57.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel57.setText("Fecha inicio:");

        jLabel60.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel60.setText("Observaciones:");

        jLabel61.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel61.setText("Fecha finalización:");

        jButton14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton14.setText("Eliminar");
        jButton14.addActionListener(this::jButton14ActionPerformed);

        jLabel62.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel62.setText("Costo total:");

        jLabel63.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel63.setText("ID del lote:");

        jTextField28.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField28.addActionListener(this::jTextField28ActionPerformed);

        jButton15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton15.setText("Limpiar");
        jButton15.addActionListener(this::jButton15ActionPerformed);

        jFormattedTextField22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField22.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jFormattedTextField23.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel84.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel84.setText("ID perfume:");

        jLabel85.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel85.setText("ID empleado:");

        jTextField29.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField29.addActionListener(this::jTextField29ActionPerformed);

        jTextField30.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField30.addActionListener(this::jTextField30ActionPerformed);

        jTextField31.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField31.addActionListener(this::jTextField31ActionPerformed);

        javax.swing.GroupLayout BajaLotesProduccionLayout = new javax.swing.GroupLayout(BajaLotesProduccion);
        BajaLotesProduccion.setLayout(BajaLotesProduccionLayout);
        BajaLotesProduccionLayout.setHorizontalGroup(
            BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajaLotesProduccionLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel84)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57)
                    .addComponent(jLabel60)
                    .addComponent(jLabel61)
                    .addComponent(jLabel63)
                    .addComponent(jLabel54)
                    .addComponent(jLabel62)
                    .addComponent(jLabel85))
                .addGap(21, 21, 21)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField22)
                    .addComponent(jFormattedTextField23)
                    .addComponent(jTextField26)
                    .addComponent(jFormattedTextField17)
                    .addComponent(jTextField27)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BajaLotesProduccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField28)
                    .addComponent(jTextField29)
                    .addComponent(jTextField30)
                    .addComponent(jTextField31))
                .addGap(96, 96, 96))
        );
        BajaLotesProduccionLayout.setVerticalGroup(
            BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajaLotesProduccionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(jTextField28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jFormattedTextField22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jFormattedTextField23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(jTextField26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jFormattedTextField17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jTextField27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BajaLotesProduccionLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel84)
                            .addComponent(jTextField30))
                        .addGap(18, 18, 18)
                        .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel85)
                            .addComponent(jTextField31)))
                    .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(jTextField29)))
                .addGap(18, 18, 18)
                .addGroup(BajaLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Baja", BajaLotesProduccion);

        CambiosLotesProduccion.setPreferredSize(new java.awt.Dimension(752, 500));

        jFormattedTextField18.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel64.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel64.setText("Cantidad producida:");

        jLabel65.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel65.setText("Control de calidad:");

        jTextField32.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField32.addActionListener(this::jTextField32ActionPerformed);

        jTextField33.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField33.addActionListener(this::jTextField33ActionPerformed);

        jLabel66.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel66.setText("Fecha inicio:");

        jLabel67.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel67.setText("Observaciones:");

        jLabel68.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel68.setText("Fecha finalización:");

        jButton16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton16.setText("Modificar");
        jButton16.addActionListener(this::jButton16ActionPerformed);

        jLabel69.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel69.setText("Costo total:");

        jLabel70.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel70.setText("ID del lote:");

        jTextField34.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField34.addActionListener(this::jTextField34ActionPerformed);

        jButton17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton17.setText("Limpiar");
        jButton17.addActionListener(this::jButton17ActionPerformed);

        jFormattedTextField24.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField24.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jFormattedTextField25.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField25.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel86.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel86.setText("ID perfume:");

        jLabel87.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel87.setText("ID empleado:");

        jTextField35.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField35.addActionListener(this::jTextField35ActionPerformed);

        jTextField36.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField36.addActionListener(this::jTextField36ActionPerformed);

        jTextField37.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField37.addActionListener(this::jTextField37ActionPerformed);

        javax.swing.GroupLayout CambiosLotesProduccionLayout = new javax.swing.GroupLayout(CambiosLotesProduccion);
        CambiosLotesProduccion.setLayout(CambiosLotesProduccionLayout);
        CambiosLotesProduccionLayout.setHorizontalGroup(
            CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiosLotesProduccionLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel86)
                    .addComponent(jLabel65)
                    .addComponent(jLabel66)
                    .addComponent(jLabel67)
                    .addComponent(jLabel68)
                    .addComponent(jLabel70)
                    .addComponent(jLabel64)
                    .addComponent(jLabel69)
                    .addComponent(jLabel87))
                .addGap(21, 21, 21)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField24)
                    .addComponent(jFormattedTextField25)
                    .addComponent(jTextField32)
                    .addComponent(jFormattedTextField18)
                    .addComponent(jTextField33)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CambiosLotesProduccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField34)
                    .addComponent(jTextField35)
                    .addComponent(jTextField36)
                    .addComponent(jTextField37))
                .addGap(96, 96, 96))
        );
        CambiosLotesProduccionLayout.setVerticalGroup(
            CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiosLotesProduccionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(jTextField34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(jFormattedTextField24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(jFormattedTextField25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jTextField32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(jFormattedTextField18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(jTextField33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CambiosLotesProduccionLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel86)
                            .addComponent(jTextField36))
                        .addGap(18, 18, 18)
                        .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel87)
                            .addComponent(jTextField37)))
                    .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel67)
                        .addComponent(jTextField35)))
                .addGap(18, 18, 18)
                .addGroup(CambiosLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Cambios", CambiosLotesProduccion);

        BuscarLotesProduccion.setPreferredSize(new java.awt.Dimension(752, 500));

        jFormattedTextField19.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel71.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel71.setText("Cantidad producida:");

        jLabel72.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel72.setText("Control de calidad:");

        jTextField38.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField38.addActionListener(this::jTextField38ActionPerformed);

        jTextField39.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField39.addActionListener(this::jTextField39ActionPerformed);

        jLabel73.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel73.setText("Fecha inicio:");

        jLabel74.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel74.setText("Observaciones:");

        jLabel75.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel75.setText("Fecha finalización:");

        jButton18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton18.setText("Buscar");
        jButton18.addActionListener(this::jButton18ActionPerformed);

        jLabel76.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel76.setText("Costo total:");

        jLabel77.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel77.setText("ID del lote:");

        jTextField40.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField40.addActionListener(this::jTextField40ActionPerformed);

        jButton19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton19.setText("Limpiar");
        jButton19.addActionListener(this::jButton19ActionPerformed);

        jFormattedTextField26.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField26.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jFormattedTextField27.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField27.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel88.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel88.setText("ID perfume:");

        jLabel89.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel89.setText("ID empleado:");

        jTextField41.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField41.addActionListener(this::jTextField41ActionPerformed);

        jTextField42.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField42.addActionListener(this::jTextField42ActionPerformed);

        jTextField43.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField43.addActionListener(this::jTextField43ActionPerformed);

        javax.swing.GroupLayout BuscarLotesProduccionLayout = new javax.swing.GroupLayout(BuscarLotesProduccion);
        BuscarLotesProduccion.setLayout(BuscarLotesProduccionLayout);
        BuscarLotesProduccionLayout.setHorizontalGroup(
            BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLotesProduccionLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel88)
                    .addComponent(jLabel72)
                    .addComponent(jLabel73)
                    .addComponent(jLabel74)
                    .addComponent(jLabel75)
                    .addComponent(jLabel77)
                    .addComponent(jLabel71)
                    .addComponent(jLabel76)
                    .addComponent(jLabel89))
                .addGap(21, 21, 21)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField26)
                    .addComponent(jFormattedTextField27)
                    .addComponent(jTextField38)
                    .addComponent(jFormattedTextField19)
                    .addComponent(jTextField39)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarLotesProduccionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField40)
                    .addComponent(jTextField41)
                    .addComponent(jTextField42)
                    .addComponent(jTextField43))
                .addGap(96, 96, 96))
        );
        BuscarLotesProduccionLayout.setVerticalGroup(
            BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLotesProduccionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(jTextField40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(jFormattedTextField26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75)
                    .addComponent(jFormattedTextField27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(jTextField38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(jFormattedTextField19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jTextField39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarLotesProduccionLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel88)
                            .addComponent(jTextField42))
                        .addGap(18, 18, 18)
                        .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel89)
                            .addComponent(jTextField43)))
                    .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel74)
                        .addComponent(jTextField41)))
                .addGap(18, 18, 18)
                .addGroup(BuscarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Buscar", BuscarLotesProduccion);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jTable1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Lote", "Fecha inicio", "Fecha fin", "Cantidad producida", "Costo total", "Control de calidad", "Observaciones", "ID perfume", "ID empleado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout MostrarLotesProduccionLayout = new javax.swing.GroupLayout(MostrarLotesProduccion);
        MostrarLotesProduccion.setLayout(MostrarLotesProduccionLayout);
        MostrarLotesProduccionLayout.setHorizontalGroup(
            MostrarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        MostrarLotesProduccionLayout.setVerticalGroup(
            MostrarLotesProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mostrar todo", MostrarLotesProduccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void jTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField36ActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField38ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField41ActionPerformed

    private void jTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField42ActionPerformed

    private void jTextField43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField43ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AltaLotesProduccion;
    private javax.swing.JPanel BajaLotesProduccion;
    private javax.swing.JPanel BuscarLotesProduccion;
    private javax.swing.JPanel CambiosLotesProduccion;
    private javax.swing.JPanel MostrarLotesProduccion;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField27;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    // End of variables declaration//GEN-END:variables
}
