/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author david
 */
public class Pedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        AltaPedidos = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<>();
        jLabel57 = new javax.swing.JLabel();
        FTxTFechaPedido = new javax.swing.JFormattedTextField();
        jLabel59 = new javax.swing.JLabel();
        TxtIDFormula = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaContiene = new javax.swing.JTable();
        BtnAgregarFilaF = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox<>();
        FTxTFechaEntrega = new javax.swing.JFormattedTextField();
        jLabel75 = new javax.swing.JLabel();
        TxtIDFormula4 = new javax.swing.JTextField();
        BtnGuardarFormula = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        BajaPedidos = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox<>();
        jLabel79 = new javax.swing.JLabel();
        FTxTFechaPedido1 = new javax.swing.JFormattedTextField();
        jLabel80 = new javax.swing.JLabel();
        TxtIDFormula5 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaContiene4 = new javax.swing.JTable();
        BtnAgregarFilaF2 = new javax.swing.JButton();
        jLabel81 = new javax.swing.JLabel();
        jComboBox23 = new javax.swing.JComboBox<>();
        FTxTFechaEntrega1 = new javax.swing.JFormattedTextField();
        jLabel82 = new javax.swing.JLabel();
        TxtIDFormula6 = new javax.swing.JTextField();
        BtnGuardarFormula4 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        CambiosPedidos = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jComboBox18 = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        FTxTFechaPedido2 = new javax.swing.JFormattedTextField();
        jLabel61 = new javax.swing.JLabel();
        TxtIDFormula1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaContiene1 = new javax.swing.JTable();
        BtnAgregarFilaF1 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jComboBox24 = new javax.swing.JComboBox<>();
        FTxTFechaEntrega2 = new javax.swing.JFormattedTextField();
        jLabel83 = new javax.swing.JLabel();
        TxtIDFormula7 = new javax.swing.JTextField();
        BtnGuardarFormula1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        BuscarPedidos = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox<>();
        jLabel66 = new javax.swing.JLabel();
        FTxTFechaPedido3 = new javax.swing.JFormattedTextField();
        jLabel67 = new javax.swing.JLabel();
        TxtIDFormula2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaContiene2 = new javax.swing.JTable();
        BtnAgregarFilaF3 = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        jComboBox25 = new javax.swing.JComboBox<>();
        FTxTFechaEntrega3 = new javax.swing.JFormattedTextField();
        jLabel84 = new javax.swing.JLabel();
        TxtIDFormula8 = new javax.swing.JTextField();
        BtnGuardarFormula2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        MostrarPedidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(692, 650));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(750, 650));

        AltaPedidos.setPreferredSize(new java.awt.Dimension(737, 630));

        jLabel51.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel51.setText("Fecha de entrega:");

        jLabel52.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel52.setText("Cliente:");

        jLabel54.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel54.setText("Estado:");

        jComboBox17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Enviado", "Entregado", "Cancelado" }));

        jLabel57.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel57.setText("Fecha de pedido:");

        FTxTFechaPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaPedido.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaPedido.addActionListener(this::FTxTFechaPedidoActionPerformed);

        jLabel59.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel59.setText("ID del pedido:");

        TxtIDFormula.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula.addActionListener(this::TxtIDFormulaActionPerformed);

        jScrollPane3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Perfume", "Precio unitario", "Subtotal "
            }
        ));
        jScrollPane3.setViewportView(TablaContiene);

        BtnAgregarFilaF.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BtnAgregarFilaF.setText("Agregar fila");
        BtnAgregarFilaF.addActionListener(this::BtnAgregarFilaFActionPerformed);

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel55.setText("Productos solicitados:");

        jComboBox21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayorista", "Minorista", "Comprador en línea" }));

        FTxTFechaEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaEntrega.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaEntrega.addActionListener(this::FTxTFechaEntregaActionPerformed);

        jLabel75.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel75.setText("Monto total:");

        TxtIDFormula4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula4.addActionListener(this::TxtIDFormula4ActionPerformed);

        BtnGuardarFormula.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula.setText("Guardar");
        BtnGuardarFormula.addActionListener(this::BtnGuardarFormulaActionPerformed);

        jButton13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton13.setText("Limpiar");
        jButton13.addActionListener(this::jButton13ActionPerformed);

        javax.swing.GroupLayout AltaPedidosLayout = new javax.swing.GroupLayout(AltaPedidos);
        AltaPedidos.setLayout(AltaPedidosLayout);
        AltaPedidosLayout.setHorizontalGroup(
            AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaPedidosLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AltaPedidosLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel57)
                                .addComponent(jLabel59)
                                .addComponent(jLabel54)
                                .addComponent(jLabel51)
                                .addComponent(jLabel52)
                                .addComponent(jLabel55))
                            .addGap(18, 18, 18)
                            .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FTxTFechaPedido)
                                .addComponent(TxtIDFormula)
                                .addComponent(jComboBox17, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox21, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FTxTFechaEntrega)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(AltaPedidosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAgregarFilaF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AltaPedidosLayout.createSequentialGroup()
                                .addComponent(jLabel75)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(AltaPedidosLayout.createSequentialGroup()
                                        .addComponent(BtnGuardarFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtIDFormula4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(104, 104, 104))
        );
        AltaPedidosLayout.setVerticalGroup(
            AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltaPedidosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(TxtIDFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jComboBox21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(FTxTFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(FTxTFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel55)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgregarFilaF)
                .addGap(18, 18, 18)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDFormula4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel75))
                .addGap(37, 37, 37)
                .addGroup(AltaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Alta", AltaPedidos);

        BajaPedidos.setPreferredSize(new java.awt.Dimension(737, 630));

        jLabel76.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel76.setText("Fecha de entrega:");

        jLabel77.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel77.setText("Cliente:");

        jLabel78.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel78.setText("Estado:");

        jComboBox22.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Enviado", "Entregado", "Cancelado" }));
        jComboBox22.setEnabled(false);

        jLabel79.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel79.setText("Fecha de pedido:");

        FTxTFechaPedido1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaPedido1.setEnabled(false);
        FTxTFechaPedido1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaPedido1.addActionListener(this::FTxTFechaPedido1ActionPerformed);

        jLabel80.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel80.setText("ID del pedido:");

        TxtIDFormula5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula5.addActionListener(this::TxtIDFormula5ActionPerformed);

        jScrollPane7.setEnabled(false);
        jScrollPane7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Perfume", "Precio unitario", "Subtotal "
            }
        ));
        jScrollPane7.setViewportView(TablaContiene4);

        BtnAgregarFilaF2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BtnAgregarFilaF2.setText("Agregar fila");
        BtnAgregarFilaF2.setEnabled(false);
        BtnAgregarFilaF2.addActionListener(this::BtnAgregarFilaF2ActionPerformed);

        jLabel81.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel81.setText("Productos solicitados:");

        jComboBox23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayorista", "Minorista", "Comprador en línea" }));
        jComboBox23.setEnabled(false);

        FTxTFechaEntrega1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaEntrega1.setEnabled(false);
        FTxTFechaEntrega1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaEntrega1.addActionListener(this::FTxTFechaEntrega1ActionPerformed);

        jLabel82.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel82.setText("Monto total:");

        TxtIDFormula6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula6.setEnabled(false);
        TxtIDFormula6.addActionListener(this::TxtIDFormula6ActionPerformed);

        BtnGuardarFormula4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula4.setText("Eliminar");
        BtnGuardarFormula4.addActionListener(this::BtnGuardarFormula4ActionPerformed);

        jButton17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton17.setText("Limpiar");
        jButton17.addActionListener(this::jButton17ActionPerformed);

        javax.swing.GroupLayout BajaPedidosLayout = new javax.swing.GroupLayout(BajaPedidos);
        BajaPedidos.setLayout(BajaPedidosLayout);
        BajaPedidosLayout.setHorizontalGroup(
            BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajaPedidosLayout.createSequentialGroup()
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BajaPedidosLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAgregarFilaF2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BajaPedidosLayout.createSequentialGroup()
                                .addComponent(jLabel82)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(BajaPedidosLayout.createSequentialGroup()
                                        .addComponent(BtnGuardarFormula4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtIDFormula6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(BajaPedidosLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BajaPedidosLayout.createSequentialGroup()
                                .addComponent(jLabel81)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(BajaPedidosLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel76)
                                    .addComponent(jLabel78)
                                    .addComponent(jLabel79)
                                    .addComponent(jLabel77)
                                    .addComponent(jLabel80))
                                .addGap(29, 29, 29)
                                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FTxTFechaPedido1)
                                    .addComponent(TxtIDFormula5)
                                    .addComponent(jComboBox22, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox23, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FTxTFechaEntrega1)))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))))
                .addGap(104, 104, 104))
        );
        BajaPedidosLayout.setVerticalGroup(
            BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BajaPedidosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(TxtIDFormula5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(jComboBox23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79)
                    .addComponent(FTxTFechaPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(FTxTFechaEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78))
                .addGap(20, 20, 20)
                .addComponent(jLabel81)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgregarFilaF2)
                .addGap(18, 18, 18)
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDFormula6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel82))
                .addGap(37, 37, 37)
                .addGroup(BajaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula4)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Baja", BajaPedidos);

        CambiosPedidos.setPreferredSize(new java.awt.Dimension(737, 630));

        jLabel53.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel53.setText("Fecha de entrega:");

        jLabel56.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel56.setText("Cliente:");

        jLabel58.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel58.setText("Estado:");

        jComboBox18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Enviado", "Entregado", "Cancelado" }));
        jComboBox18.setEnabled(false);

        jLabel60.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel60.setText("Fecha de pedido:");

        FTxTFechaPedido2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaPedido2.setEnabled(false);
        FTxTFechaPedido2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaPedido2.addActionListener(this::FTxTFechaPedido2ActionPerformed);

        jLabel61.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel61.setText("ID del pedido:");

        TxtIDFormula1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula1.addActionListener(this::TxtIDFormula1ActionPerformed);

        jScrollPane4.setEnabled(false);
        jScrollPane4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Perfume", "Precio unitario", "Subtotal "
            }
        ));
        jScrollPane4.setViewportView(TablaContiene1);

        BtnAgregarFilaF1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BtnAgregarFilaF1.setText("Agregar fila");
        BtnAgregarFilaF1.setEnabled(false);
        BtnAgregarFilaF1.addActionListener(this::BtnAgregarFilaF1ActionPerformed);

        jLabel62.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel62.setText("Productos solicitados:");

        jComboBox24.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayorista", "Minorista", "Comprador en línea" }));
        jComboBox24.setEnabled(false);

        FTxTFechaEntrega2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaEntrega2.setEnabled(false);
        FTxTFechaEntrega2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaEntrega2.addActionListener(this::FTxTFechaEntrega2ActionPerformed);

        jLabel83.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel83.setText("Monto total:");

        TxtIDFormula7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula7.setEnabled(false);
        TxtIDFormula7.addActionListener(this::TxtIDFormula7ActionPerformed);

        BtnGuardarFormula1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula1.setText("Modificar");
        BtnGuardarFormula1.addActionListener(this::BtnGuardarFormula1ActionPerformed);

        jButton14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton14.setText("Limpiar");
        jButton14.addActionListener(this::jButton14ActionPerformed);

        javax.swing.GroupLayout CambiosPedidosLayout = new javax.swing.GroupLayout(CambiosPedidos);
        CambiosPedidos.setLayout(CambiosPedidosLayout);
        CambiosPedidosLayout.setHorizontalGroup(
            CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiosPedidosLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CambiosPedidosLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel60)
                                .addComponent(jLabel61)
                                .addComponent(jLabel58)
                                .addComponent(jLabel53)
                                .addComponent(jLabel56)
                                .addComponent(jLabel62))
                            .addGap(18, 18, 18)
                            .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FTxTFechaPedido2)
                                .addComponent(TxtIDFormula1)
                                .addComponent(jComboBox18, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox24, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FTxTFechaEntrega2)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(CambiosPedidosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAgregarFilaF1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CambiosPedidosLayout.createSequentialGroup()
                                .addComponent(jLabel83)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CambiosPedidosLayout.createSequentialGroup()
                                        .addComponent(BtnGuardarFormula1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtIDFormula7, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(104, 104, 104))
        );
        CambiosPedidosLayout.setVerticalGroup(
            CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiosPedidosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(TxtIDFormula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jComboBox24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(FTxTFechaPedido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(FTxTFechaEntrega2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel62)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgregarFilaF1)
                .addGap(18, 18, 18)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDFormula7, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel83))
                .addGap(37, 37, 37)
                .addGroup(CambiosPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula1)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Cambios", CambiosPedidos);

        BuscarPedidos.setPreferredSize(new java.awt.Dimension(737, 630));

        jLabel63.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel63.setText("Fecha de entrega:");

        jLabel64.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel64.setText("Cliente:");

        jLabel65.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel65.setText("Estado:");

        jComboBox19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Enviado", "Entregado", "Cancelado" }));
        jComboBox19.setEnabled(false);

        jLabel66.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel66.setText("Fecha de pedido:");

        FTxTFechaPedido3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaPedido3.setEnabled(false);
        FTxTFechaPedido3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaPedido3.addActionListener(this::FTxTFechaPedido3ActionPerformed);

        jLabel67.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel67.setText("ID del pedido:");

        TxtIDFormula2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula2.addActionListener(this::TxtIDFormula2ActionPerformed);

        jScrollPane5.setEnabled(false);
        jScrollPane5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        TablaContiene2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Perfume", "Precio unitario", "Subtotal "
            }
        ));
        jScrollPane5.setViewportView(TablaContiene2);

        BtnAgregarFilaF3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        BtnAgregarFilaF3.setText("Agregar fila");
        BtnAgregarFilaF3.setEnabled(false);
        BtnAgregarFilaF3.addActionListener(this::BtnAgregarFilaF3ActionPerformed);

        jLabel68.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel68.setText("Productos solicitados:");

        jComboBox25.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox25.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayorista", "Minorista", "Comprador en línea" }));
        jComboBox25.setEnabled(false);

        FTxTFechaEntrega3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        FTxTFechaEntrega3.setEnabled(false);
        FTxTFechaEntrega3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        FTxTFechaEntrega3.addActionListener(this::FTxTFechaEntrega3ActionPerformed);

        jLabel84.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel84.setText("Monto total:");

        TxtIDFormula8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        TxtIDFormula8.setEnabled(false);
        TxtIDFormula8.addActionListener(this::TxtIDFormula8ActionPerformed);

        BtnGuardarFormula2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardarFormula2.setText("Buscar");
        BtnGuardarFormula2.addActionListener(this::BtnGuardarFormula2ActionPerformed);

        jButton15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton15.setText("Limpiar");
        jButton15.addActionListener(this::jButton15ActionPerformed);

        javax.swing.GroupLayout BuscarPedidosLayout = new javax.swing.GroupLayout(BuscarPedidos);
        BuscarPedidos.setLayout(BuscarPedidosLayout);
        BuscarPedidosLayout.setHorizontalGroup(
            BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarPedidosLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BuscarPedidosLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel66)
                                .addComponent(jLabel67)
                                .addComponent(jLabel65)
                                .addComponent(jLabel63)
                                .addComponent(jLabel64)
                                .addComponent(jLabel68))
                            .addGap(18, 18, 18)
                            .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FTxTFechaPedido3)
                                .addComponent(TxtIDFormula2)
                                .addComponent(jComboBox19, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox25, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FTxTFechaEntrega3)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(BuscarPedidosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAgregarFilaF3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BuscarPedidosLayout.createSequentialGroup()
                                .addComponent(jLabel84)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(BuscarPedidosLayout.createSequentialGroup()
                                        .addComponent(BtnGuardarFormula2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtIDFormula8, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(104, 104, 104))
        );
        BuscarPedidosLayout.setVerticalGroup(
            BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarPedidosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(TxtIDFormula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jComboBox25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(FTxTFechaPedido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(FTxTFechaEntrega3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel68)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgregarFilaF3)
                .addGap(18, 18, 18)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDFormula8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel84))
                .addGap(37, 37, 37)
                .addGroup(BuscarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarFormula2)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Buscar", BuscarPedidos);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pedido", "ID Cliente", "Fecha pedido", "Fecha entrega", "Estado", "Total"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout MostrarPedidosLayout = new javax.swing.GroupLayout(MostrarPedidos);
        MostrarPedidos.setLayout(MostrarPedidosLayout);
        MostrarPedidosLayout.setHorizontalGroup(
            MostrarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        MostrarPedidosLayout.setVerticalGroup(
            MostrarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mostrar todo", MostrarPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarFormulaActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int fila = jTable2.getSelectedRow();

        if (fila != -1) {

            String id = jTable2.getValueAt(fila, 0).toString();
            mostrarDetallesPedido(id);
        }
        }
        private void mostrarDetallesPedido(String id) {
            javax.swing.JDialog ventanaDetalle = new javax.swing.JDialog();
            ventanaDetalle.setTitle("Detalles del pedido " + id);
            ventanaDetalle.setSize(500, 300);
            ventanaDetalle.setLocationRelativeTo(this);
            ventanaDetalle.setModal(true);

            String[] columnas = {"Perfume", "Precio unitario", "Subtotal"};
            javax.swing.table.DefaultTableModel modeloDetalle = new javax.swing.table.DefaultTableModel(columnas, 0);
            javax.swing.JTable tablaDetalle = new javax.swing.JTable(modeloDetalle);
            javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tablaDetalle);
            ventanaDetalle.add(scroll);
            ventanaDetalle.setVisible(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void TxtIDFormula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula4ActionPerformed

    private void FTxTFechaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaEntregaActionPerformed

    private void BtnAgregarFilaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFilaFActionPerformed
        // TODO add your handling code here
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaContiene.getModel();
        modelo.addRow(new Object[]{"", "", ""});
    }//GEN-LAST:event_BtnAgregarFilaFActionPerformed

    private void TxtIDFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormulaActionPerformed

    private void FTxTFechaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaPedidoActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void FTxTFechaPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaPedido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaPedido1ActionPerformed

    private void TxtIDFormula5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula5ActionPerformed

    private void BtnAgregarFilaF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFilaF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarFilaF2ActionPerformed

    private void FTxTFechaEntrega1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaEntrega1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaEntrega1ActionPerformed

    private void TxtIDFormula6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula6ActionPerformed

    private void BtnGuardarFormula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormula4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarFormula4ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void FTxTFechaPedido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaPedido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaPedido2ActionPerformed

    private void TxtIDFormula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula1ActionPerformed

    private void BtnAgregarFilaF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFilaF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarFilaF1ActionPerformed

    private void FTxTFechaEntrega2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaEntrega2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaEntrega2ActionPerformed

    private void TxtIDFormula7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula7ActionPerformed

    private void BtnGuardarFormula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarFormula1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void FTxTFechaPedido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaPedido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaPedido3ActionPerformed

    private void TxtIDFormula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula2ActionPerformed

    private void BtnAgregarFilaF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFilaF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarFilaF3ActionPerformed

    private void FTxTFechaEntrega3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTxTFechaEntrega3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTxTFechaEntrega3ActionPerformed

    private void TxtIDFormula8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDFormula8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDFormula8ActionPerformed

    private void BtnGuardarFormula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarFormula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarFormula2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AltaPedidos;
    private javax.swing.JPanel BajaPedidos;
    private javax.swing.JButton BtnAgregarFilaF;
    private javax.swing.JButton BtnAgregarFilaF1;
    private javax.swing.JButton BtnAgregarFilaF2;
    private javax.swing.JButton BtnAgregarFilaF3;
    private javax.swing.JButton BtnGuardarFormula;
    private javax.swing.JButton BtnGuardarFormula1;
    private javax.swing.JButton BtnGuardarFormula2;
    private javax.swing.JButton BtnGuardarFormula4;
    private javax.swing.JPanel BuscarPedidos;
    private javax.swing.JPanel CambiosPedidos;
    private javax.swing.JFormattedTextField FTxTFechaEntrega;
    private javax.swing.JFormattedTextField FTxTFechaEntrega1;
    private javax.swing.JFormattedTextField FTxTFechaEntrega2;
    private javax.swing.JFormattedTextField FTxTFechaEntrega3;
    private javax.swing.JFormattedTextField FTxTFechaPedido;
    private javax.swing.JFormattedTextField FTxTFechaPedido1;
    private javax.swing.JFormattedTextField FTxTFechaPedido2;
    private javax.swing.JFormattedTextField FTxTFechaPedido3;
    private javax.swing.JPanel MostrarPedidos;
    private javax.swing.JTable TablaContiene;
    private javax.swing.JTable TablaContiene1;
    private javax.swing.JTable TablaContiene2;
    private javax.swing.JTable TablaContiene4;
    private javax.swing.JTextField TxtIDFormula;
    private javax.swing.JTextField TxtIDFormula1;
    private javax.swing.JTextField TxtIDFormula2;
    private javax.swing.JTextField TxtIDFormula4;
    private javax.swing.JTextField TxtIDFormula5;
    private javax.swing.JTextField TxtIDFormula6;
    private javax.swing.JTextField TxtIDFormula7;
    private javax.swing.JTextField TxtIDFormula8;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox24;
    private javax.swing.JComboBox<String> jComboBox25;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
