/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class Proveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CmbPrograma = new javax.swing.JComboBox<>();
        TxtContacto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtApellidoPaterno = new javax.swing.JTextField();
        TxtApellidoMaterno = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtCondicionesPago = new javax.swing.JTextField();
        TxtCalificacion = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        TxtIDProveedor = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        TxtContactoBaja = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        TxtApellidoPaternoBaja = new javax.swing.JTextField();
        TxtApellidoMaternoBaja = new javax.swing.JTextField();
        TxtTelefonoBaja = new javax.swing.JTextField();
        TxtDireccionBaja = new javax.swing.JTextField();
        TxtCondicionesPagoBaja = new javax.swing.JTextField();
        TxtCalificacionBaja = new javax.swing.JTextField();
        BtnBaja = new javax.swing.JButton();
        BtnLimpiarBaja = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        TxtIDProveedorBaja = new javax.swing.JTextField();
        TxtNombreBaja = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        TxtContactoModificar = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        TxtApellidoPaternoModificar = new javax.swing.JTextField();
        TxtApellidoMaternoModificar = new javax.swing.JTextField();
        TxtTelefonoModificar = new javax.swing.JTextField();
        TxtDireccionModificar = new javax.swing.JTextField();
        TxtCondicionesPagoModificar = new javax.swing.JTextField();
        TxtCalificacionModificar = new javax.swing.JTextField();
        BtnModificar = new javax.swing.JButton();
        BtnLimpiarModificar = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        TxtIDProveedorModificar = new javax.swing.JTextField();
        TxtNombreModificar = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        TxtContactoBuscar = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        TxtApellidoPaternoBuscar = new javax.swing.JTextField();
        TxtApellidoMaternoBuscar = new javax.swing.JTextField();
        TxtTelefonoBuscar = new javax.swing.JTextField();
        TxtDireccionBuscar = new javax.swing.JTextField();
        TxtCondicionesPagoBuscar = new javax.swing.JTextField();
        TxtCalificacionBuscar = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnLimpiarBuscar = new javax.swing.JButton();
        jLabel67 = new javax.swing.JLabel();
        TxtNombreBuscar = new javax.swing.JTextField();
        TxtIDProveedorBuscar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del contacto:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Tipo:");

        CmbPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio", "Producto" }));
        CmbPrograma.addActionListener(this::CmbProgramaActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Apellido paterno:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("Apellido materno:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Teléfono:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Condiciones de pago:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Calificación:");

        BtnGuardar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);

        BtnLimpiar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnLimpiar.setText("Limpiar");

        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel37.setText("ID proveedor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtIDProveedor)
                    .addComponent(TxtNombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnGuardar)
                        .addGap(174, 174, 174)
                        .addComponent(BtnLimpiar))
                    .addComponent(CmbPrograma, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoMaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCalificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtContacto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCondicionesPago, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoPaterno, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CmbPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtApellidoMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtCondicionesPago, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnGuardar))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Alta", jPanel1);

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel38.setText("Nombre:");

        jLabel39.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel39.setText("Nombre del contacto:");

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel40.setText("Tipo:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio", "Producto" }));
        jComboBox5.setEnabled(false);

        TxtContactoBaja.setEnabled(false);

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel41.setText("Apellido paterno:");

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel42.setText("Apellido materno:");

        jLabel43.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel43.setText("Teléfono:");

        jLabel44.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel44.setText("Dirección:");

        jLabel45.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel45.setText("Condiciones de pago:");

        jLabel46.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel46.setText("Calificación:");

        TxtApellidoPaternoBaja.setEnabled(false);

        TxtApellidoMaternoBaja.setEnabled(false);

        TxtTelefonoBaja.setEnabled(false);

        TxtDireccionBaja.setEnabled(false);

        TxtCondicionesPagoBaja.setEnabled(false);

        TxtCalificacionBaja.setEnabled(false);

        BtnBaja.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnBaja.setText("Eliminar");
        BtnBaja.addActionListener(this::BtnBajaActionPerformed);

        BtnLimpiarBaja.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnLimpiarBaja.setText("Limpiar");

        jLabel47.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel47.setText("ID proveedor:");

        TxtNombreBaja.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtIDProveedorBaja)
                    .addComponent(TxtNombreBaja)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(BtnBaja)
                        .addGap(174, 174, 174)
                        .addComponent(BtnLimpiarBaja))
                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTelefonoBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoMaternoBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCalificacionBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtContactoBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCondicionesPagoBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtDireccionBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoPaternoBaja, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(145, 145, 145))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDProveedorBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(TxtNombreBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(TxtContactoBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(TxtApellidoPaternoBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(TxtApellidoMaternoBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(TxtTelefonoBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(TxtDireccionBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(TxtCondicionesPagoBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(TxtCalificacionBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiarBaja)
                    .addComponent(BtnBaja))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Baja", jPanel6);

        jLabel48.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel48.setText("Nombre:");

        jLabel49.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel49.setText("Nombre del contacto:");

        jLabel50.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel50.setText("Tipo:");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio", "Producto" }));

        jLabel51.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel51.setText("Apellido paterno:");

        jLabel52.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel52.setText("Apellido materno:");

        jLabel53.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel53.setText("Teléfono:");

        jLabel54.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel54.setText("Dirección:");

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel55.setText("Condiciones de pago:");

        jLabel56.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel56.setText("Calificación:");

        BtnModificar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(this::BtnModificarActionPerformed);

        BtnLimpiarModificar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnLimpiarModificar.setText("Limpiar");

        jLabel57.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel57.setText("ID proveedor:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtIDProveedorModificar)
                    .addComponent(TxtNombreModificar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(BtnModificar)
                        .addGap(174, 174, 174)
                        .addComponent(BtnLimpiarModificar))
                    .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTelefonoModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoMaternoModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCalificacionModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtContactoModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCondicionesPagoModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtDireccionModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoPaternoModificar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(145, 145, 145))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDProveedorModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(TxtNombreModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(TxtContactoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(TxtApellidoPaternoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(TxtApellidoMaternoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(TxtTelefonoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(TxtDireccionModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(TxtCondicionesPagoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(TxtCalificacionModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiarModificar)
                    .addComponent(BtnModificar))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Cambios", jPanel7);

        jLabel58.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel58.setText("Nombre:");

        jLabel59.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel59.setText("Nombre del contacto:");

        jLabel60.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel60.setText("Tipo:");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio", "Producto" }));
        jComboBox7.setEnabled(false);

        TxtContactoBuscar.setEnabled(false);

        jLabel61.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel61.setText("Apellido paterno:");

        jLabel62.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel62.setText("Apellido materno:");

        jLabel63.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel63.setText("Teléfono:");

        jLabel64.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel64.setText("Dirección:");

        jLabel65.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel65.setText("Condiciones de pago:");

        jLabel66.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel66.setText("Calificación:");

        TxtApellidoPaternoBuscar.setEnabled(false);

        TxtApellidoMaternoBuscar.setEnabled(false);

        TxtTelefonoBuscar.setEnabled(false);

        TxtDireccionBuscar.setEnabled(false);

        TxtCondicionesPagoBuscar.setEnabled(false);

        TxtCalificacionBuscar.setEnabled(false);

        BtnBuscar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(this::BtnBuscarActionPerformed);

        BtnLimpiarBuscar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        BtnLimpiarBuscar.setText("Limpiar");

        jLabel67.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel67.setText("ID proveedor:");

        TxtNombreBuscar.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel66, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtIDProveedorBuscar)
                    .addComponent(TxtNombreBuscar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(BtnBuscar)
                        .addGap(174, 174, 174)
                        .addComponent(BtnLimpiarBuscar))
                    .addComponent(jComboBox7, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTelefonoBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoMaternoBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCalificacionBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtContactoBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCondicionesPagoBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtDireccionBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtApellidoPaternoBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(145, 145, 145))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIDProveedorBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(TxtNombreBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(TxtContactoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(TxtApellidoPaternoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(TxtApellidoMaternoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(TxtTelefonoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(TxtDireccionBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(TxtCondicionesPagoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(TxtCalificacionBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiarBuscar)
                    .addComponent(BtnBuscar))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Buscar", jPanel8);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID proveedor", "Nombre", "Tipo", "Nombre Contacto", "Apellido paterno", "Apellido materno", "Teléfono", "Dirección", "Condiciones de pago", "Calificación"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mostrar todo", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
                try
        {
                if (!(TxtIDProveedor.getText().isEmpty()) && !(TxtNombre.getText().isEmpty())  
                && !(TxtApellidoMaterno.getText().isEmpty()) && !(TxtApellidoPaterno.getText().isEmpty())  
                && !(TxtCalificacion.getText().isEmpty()) && !(TxtCondicionesPago.getText().isEmpty()) 
                && !(TxtTelefono.getText().isEmpty()) && !(TxtDireccion.getText().isEmpty())  
                && !(TxtContacto.getText().isEmpty()))
            {
                Modelos.Proveedores Ob = new Modelos.Proveedores();
                
                int Id = Integer.parseInt(TxtIDProveedor.getText().trim());
                Ob.setId_proveedor(Id);
                Ob.setContacto_nombre(TxtContacto.getText().trim());
                Ob.setNombre_proveedor(TxtNombre.getText().trim());
                Ob.setContacto_ap_paterno(TxtApellidoPaterno.getText().trim());
                Ob.setContacto_ap_materno(TxtApellidoMaterno.getText().trim());
                Ob.setTelefono(TxtTelefono.getText().trim());
                Ob.setDireccion(TxtDireccion.getText().trim());
                Ob.setCondiciones_de_pago(TxtCondicionesPago.getText().trim());

                float Calificacion = Float.parseFloat(TxtCalificacion.getText().trim());            
                Ob.setCalificacion(Calificacion);

                
                String Tipo = (String) CmbPrograma.getSelectedItem();
                Ob.setTipo_servicio(Tipo);
                

                
                Ob.guardar();
                
                TxtIDProveedor.setText("");
                TxtNombre.setText("");
                TxtApellidoPaterno.setText("");
                TxtApellidoMaterno.setText("");
                TxtTelefono.setText("");
                TxtDireccion.setText("");
                TxtCondicionesPago.setText("");
                TxtCalificacion.setText("");
                
                javax.swing.JOptionPane.showMessageDialog(this, "Registro exitoso");                
        }
        } 
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBajaActionPerformed
        // TODO add your handling code here:
        try {
            Modelos.Proveedores Ob = new Modelos.Proveedores();
            Ob.Borrar(Integer.parseInt(TxtIDProveedorBaja.getText())); //
            javax.swing.JOptionPane.showMessageDialog(this, "Perfume eliminado.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnBajaActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validamos los campos de la pestaña "CAMBIOS" (tienen el sufijo Modificar)
            if (!TxtIDProveedorModificar.getText().isEmpty() && !TxtNombreModificar.getText().isEmpty()  
                && !TxtContactoModificar.getText().isEmpty() && !TxtApellidoPaternoModificar.getText().isEmpty()  
                && !TxtApellidoMaternoModificar.getText().isEmpty() && !TxtTelefonoModificar.getText().isEmpty() 
                && !TxtDireccionModificar.getText().isEmpty() && !TxtCondicionesPagoModificar.getText().isEmpty()  
                && !TxtCalificacionModificar.getText().isEmpty())
            {
                
                Modelos.Proveedores Ob = new Modelos.Proveedores();
            
                // 2. Asignamos los valores de las cajas de texto "Modificar" al objeto
                // ID (Entero)
                Ob.setId_proveedor(Integer.parseInt(TxtIDProveedorModificar.getText().trim()));
                
                // Textos (Strings)
                Ob.setNombre_proveedor(TxtNombreModificar.getText().trim());
                Ob.setTipo_servicio((String) jComboBox6.getSelectedItem()); // El Combo de la pestaña modificar es el 6
                Ob.setContacto_nombre(TxtContactoModificar.getText().trim());
                Ob.setContacto_ap_paterno(TxtApellidoPaternoModificar.getText().trim());
                Ob.setContacto_ap_materno(TxtApellidoMaternoModificar.getText().trim());
                Ob.setTelefono(TxtTelefonoModificar.getText().trim());
                Ob.setDireccion(TxtDireccionModificar.getText().trim());
                Ob.setCondiciones_de_pago(TxtCondicionesPagoModificar.getText().trim());
                
                // Calificación (Float)
                Ob.setCalificacion(Float.parseFloat(TxtCalificacionModificar.getText().trim()));
                
                // 3. Ejecutamos la modificación en BD
                Ob.Modificar();
                
                // 4. Limpiamos las cajas de la pestaña Modificar
                TxtIDProveedorModificar.setText("");
                TxtNombreModificar.setText("");
                TxtContactoModificar.setText("");
                TxtApellidoPaternoModificar.setText("");
                TxtApellidoMaternoModificar.setText("");
                TxtTelefonoModificar.setText("");
                TxtDireccionModificar.setText("");
                TxtCondicionesPagoModificar.setText("");
                TxtCalificacionModificar.setText("");
                
                javax.swing.JOptionPane.showMessageDialog(this, "Proveedor modificado con éxito");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos para modificar.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validar que el campo ID no esté vacío
            if (!TxtIDProveedorBuscar.getText().isEmpty()) {
                
                Modelos.Proveedores Ob = new Modelos.Proveedores();
                
                // 2. Convertir el ID a entero
                int id = Integer.parseInt(TxtIDProveedorBuscar.getText().trim());
                
                // 3. Ejecutar la búsqueda en la Base de Datos
                if (Ob.Buscar(id)) {
                    
                    // 4. Si se encuentra, llenamos los campos de la pestaña BUSCAR
                    TxtNombreBuscar.setText(Ob.getNombre_proveedor());
                    
                    // Seleccionamos el item correcto en el ComboBox de BUSCAR (jComboBox7)
                    jComboBox7.setSelectedItem(Ob.getTipo_servicio()); 
                    
                    TxtContactoBuscar.setText(Ob.getContacto_nombre());
                    TxtApellidoPaternoBuscar.setText(Ob.getContacto_ap_paterno());
                    TxtApellidoMaternoBuscar.setText(Ob.getContacto_ap_materno());
                    TxtTelefonoBuscar.setText(Ob.getTelefono());
                    TxtDireccionBuscar.setText(Ob.getDireccion());
                    TxtCondicionesPagoBuscar.setText(Ob.getCondiciones_de_pago());
                    
                    // Convertimos la calificación (float) a texto para mostrarla
                    TxtCalificacionBuscar.setText(String.valueOf(Ob.getCalificacion()));

                    JOptionPane.showMessageDialog(this, "Proveedor encontrado.");
                    
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró ningún proveedor con ese ID.");
                    // Opcional: Limpiar campos si no se encuentra
                    BtnLimpiarBuscar.doClick(); 
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor escribe un ID para buscar.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.toString());
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void CmbProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbProgramaActionPerformed

    
    private void CargarTabla() {
        try {
            Modelos.Proveedores Ob = new Modelos.Proveedores();
            
            // Aquí llamamos al método Mostrar() que acabas de crear en el Modelo
            jTable1.setModel(Ob.Mostrar());
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.toString());
        }
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBaja;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnLimpiarBaja;
    private javax.swing.JButton BtnLimpiarBuscar;
    private javax.swing.JButton BtnLimpiarModificar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JComboBox<String> CmbPrograma;
    private javax.swing.JTextField TxtApellidoMaterno;
    private javax.swing.JTextField TxtApellidoMaternoBaja;
    private javax.swing.JTextField TxtApellidoMaternoBuscar;
    private javax.swing.JTextField TxtApellidoMaternoModificar;
    private javax.swing.JTextField TxtApellidoPaterno;
    private javax.swing.JTextField TxtApellidoPaternoBaja;
    private javax.swing.JTextField TxtApellidoPaternoBuscar;
    private javax.swing.JTextField TxtApellidoPaternoModificar;
    private javax.swing.JTextField TxtCalificacion;
    private javax.swing.JTextField TxtCalificacionBaja;
    private javax.swing.JTextField TxtCalificacionBuscar;
    private javax.swing.JTextField TxtCalificacionModificar;
    private javax.swing.JTextField TxtCondicionesPago;
    private javax.swing.JTextField TxtCondicionesPagoBaja;
    private javax.swing.JTextField TxtCondicionesPagoBuscar;
    private javax.swing.JTextField TxtCondicionesPagoModificar;
    private javax.swing.JTextField TxtContacto;
    private javax.swing.JTextField TxtContactoBaja;
    private javax.swing.JTextField TxtContactoBuscar;
    private javax.swing.JTextField TxtContactoModificar;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDireccionBaja;
    private javax.swing.JTextField TxtDireccionBuscar;
    private javax.swing.JTextField TxtDireccionModificar;
    private javax.swing.JTextField TxtIDProveedor;
    private javax.swing.JTextField TxtIDProveedorBaja;
    private javax.swing.JTextField TxtIDProveedorBuscar;
    private javax.swing.JTextField TxtIDProveedorModificar;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNombreBaja;
    private javax.swing.JTextField TxtNombreBuscar;
    private javax.swing.JTextField TxtNombreModificar;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JTextField TxtTelefonoBaja;
    private javax.swing.JTextField TxtTelefonoBuscar;
    private javax.swing.JTextField TxtTelefonoModificar;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

